---
- hosts: all
  become: yes
  tasks:

  - name: update repo index
    apt:
      update_cache: yes

  - name: install apache2
    apt:
      name: apache2

  - name: add PHP support
    apt:
      name: libapache2-mod-php
