---
- name: Install Docker
  hosts: all
  become: yes
  tasks:
    - name: Update apt
      apt:
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: Update dnf
      dnf:
        name: '*'
        state: latest
      when: ansible_distribution == "CentOS"

    - name: Install prereq (Ubuntu)
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: Install prereq (CentOS)
      dnf:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
          - python3-pip
          - ca-certificates
          - curl
        state: present
      when: ansible_distribution == "CentOS"

    - name: Add Docker official GPG key (Ubuntu)
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: Add Docker official GPG key (CentOS)
      rpm_key:
        key: https://download.docker.com/linux/centos/gpg
        state: present
      when: ansible_distribution == "CentOS"

    - name: Add Docker repo (Ubuntu)
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: Add Docker repo (CentOS)
      yum_repository:
        name: docker-ce
        description: Docker REPO
        baseurl: "https://download.docker.com/linux/centos/{{ ansible_distribution_major_version }}/x86_64/stable"
        gpgcheck: yes
        enabled: yes
      when: ansible_distribution == "CentOS"

    - name: Install Docker Engine (Ubuntu)
      apt:
        name: docker-ce
        state: present
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: Install Docker Engine (CentOS)
      dnf:
        name: docker-ce
        state: present
      when: ansible_distribution == "CentOS"
    
    - name: Install Docker SDK for Python (Ubuntu)
      apt:
        name: python3-docker
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: Install Docker SDK for Python (CentOS)
      pip:
        name: docker
        executable: pip3
      when: ansible_distribution == "CentOS"


    - name: Docker start and enable on boot
      service:
        name: docker
        state: started
        enabled: yes
